/**
 * Curated table of the misspellings children actually produce.
 *
 * This is the highest-value layer in the whole spell checker: it is instant,
 * free, needs no dictionary, and catches the large majority of what Cooper
 * will write. A generic dictionary suggests plausible-but-wrong alternatives
 * for these ("gos" → "gas", "gods", "gross"); this table just knows.
 *
 * It grows: every correction she accepts gets appended to her profile and
 * merged in at runtime.
 */
export const COMMON_MISSPELLINGS: Record<string, string> = {
  // High-frequency verbs
  gos: 'goes',
  goeing: 'going',
  gose: 'goes',
  sed: 'said',
  siad: 'said',
  saeid: 'said',
  cam: 'came',
  cume: 'come',
  runing: 'running',
  runned: 'ran',
  geting: 'getting',
  puting: 'putting',
  siting: 'sitting',
  stoped: 'stopped',
  jumpd: 'jumped',
  jumpt: 'jumped',
  looked: 'looked',
  lookt: 'looked',
  walkt: 'walked',
  tryed: 'tried',
  cryed: 'cried',
  flyed: 'flew',
  catched: 'caught',
  cort: 'caught',
  cought: 'caught',
  brort: 'brought',
  brot: 'brought',
  thort: 'thought',
  thot: 'thought',
  thout: 'thought',
  boght: 'bought',
  tuk: 'took',
  wen: 'when',
  wnet: 'went',
  whent: 'went',
  becuase: 'because',
  becuse: 'because',
  becos: 'because',
  becaus: 'because',
  cos: 'because',
  coz: 'because',
  bicos: 'because',

  // Pronouns and function words
  thay: 'they',
  thier: 'their',
  theyre: "they're",
  ther: 'there',
  thre: 'there',
  wich: 'which',
  witch: 'which',
  wot: 'what',
  wat: 'what',
  wher: 'where',
  wheres: "where's",
  becouse: 'because',
  allot: 'a lot',
  alot: 'a lot',
  aswell: 'as well',
  infront: 'in front',
  ofcourse: 'of course',
  everytime: 'every time',
  aswel: 'as well',
  its: "it's",
  dont: "don't",
  didnt: "didn't",
  cant: "can't",
  wont: "won't",
  couldnt: "couldn't",
  wouldnt: "wouldn't",
  shouldnt: "shouldn't",
  isnt: "isn't",
  wasnt: "wasn't",
  havent: "haven't",
  hasnt: "hasn't",
  im: "I'm",
  ive: "I've",
  ill: "I'll",
  thats: "that's",
  hes: "he's",
  shes: "she's",
  theres: "there's",

  // Common nouns
  freind: 'friend',
  frend: 'friend',
  freinds: 'friends',
  peopel: 'people',
  peaple: 'people',
  peopele: 'people',
  familey: 'family',
  famly: 'family',
  bruther: 'brother',
  bruvver: 'brother',
  siter: 'sister',
  muther: 'mother',
  farther: 'father',
  hous: 'house',
  hause: 'house',
  skool: 'school',
  scool: 'school',
  wold: 'world',
  worl: 'world',
  anamal: 'animal',
  anmal: 'animal',
  animel: 'animal',
  monkie: 'monkey',
  munkey: 'monkey',
  wolfs: 'wolves',
  foxs: 'foxes',
  mouses: 'mice',
  childs: 'children',
  childrens: 'children',

  // Descriptive words
  beutiful: 'beautiful',
  beatiful: 'beautiful',
  butiful: 'beautiful',
  scarey: 'scary',
  scarry: 'scary',
  angrey: 'angry',
  hungy: 'hungry',
  hungery: 'hungry',
  diffrent: 'different',
  diferent: 'different',
  favrite: 'favourite',
  favourate: 'favourite',
  favorate: 'favourite',
  intresting: 'interesting',
  intersting: 'interesting',
  suprised: 'surprised',
  suprise: 'surprise',
  surpised: 'surprised',
  exsited: 'excited',
  exited: 'excited',
  excitd: 'excited',
  terrable: 'terrible',
  horrable: 'horrible',
  increadible: 'incredible',
  amazeing: 'amazing',
  huuge: 'huge',
  massiv: 'massive',
  enourmous: 'enormous',
  enormus: 'enormous',
  gigantick: 'gigantic',

  // Story words she'll reach for constantly
  advencher: 'adventure',
  adventer: 'adventure',
  adventre: 'adventure',
  mistery: 'mystery',
  mistary: 'mystery',
  tresure: 'treasure',
  treshure: 'treasure',
  magick: 'magic',
  majic: 'magic',
  majick: 'magic',
  wizzard: 'wizard',
  dragan: 'dragon',
  dragun: 'dragon',
  castel: 'castle',
  cassle: 'castle',
  forrest: 'forest',
  monstor: 'monster',
  monsta: 'monster',
  goast: 'ghost',
  gost: 'ghost',
  skeliton: 'skeleton',
  vilage: 'village',
  villige: 'village',
  jorney: 'journey',
  jurney: 'journey',
  esape: 'escape',
  escpae: 'escape',

  // Endings and general shapes
  wich_one: 'which one',
  alway: 'always',
  allways: 'always',
  agian: 'again',
  agen: 'again',
  agin: 'again',
  anuther: 'another',
  anouther: 'another',
  sudenly: 'suddenly',
  sudnly: 'suddenly',
  suddnely: 'suddenly',
  quikly: 'quickly',
  quickley: 'quickly',
  slowley: 'slowly',
  realy: 'really',
  relly: 'really',
  verey: 'very',
  probly: 'probably',
  probaly: 'probably',
  definately: 'definitely',
  defiantly: 'definitely',
  seperate: 'separate',
  recieve: 'receive',
  beleive: 'believe',
  belive: 'believe',
  acheive: 'achieve',
  wierd: 'weird',
  freinly: 'friendly',
  nite: 'night',
  lite: 'light',
  rite: 'right',
  brite: 'bright',
  fite: 'fight',
  mite: 'might',
  tho: 'though',
  thru: 'through',
  throught: 'through',
  thourgh: 'through',
  enuff: 'enough',
  enuf: 'enough',
  laff: 'laugh',
  laf: 'laugh',
  larf: 'laugh',
  cuz: 'because',
  wanna: 'want to',
  gonna: 'going to',
  gotta: 'got to',
  kinda: 'kind of',
  sorta: 'sort of',
  outa: 'out of',
  lotsa: 'lots of',
};

/** Case-insensitive lookup, preserving her capitalisation. */
export function lookupMisspelling(word: string): string | null {
  const lower = word.toLowerCase();
  const fix = COMMON_MISSPELLINGS[lower];
  if (!fix) return null;
  return matchCase(word, fix);
}

export function matchCase(original: string, replacement: string): string {
  if (original === original.toUpperCase() && original.length > 1) {
    return replacement.toUpperCase();
  }
  if (original[0] && original[0] === original[0].toUpperCase()) {
    return replacement[0]!.toUpperCase() + replacement.slice(1);
  }
  return replacement;
}
